// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ4HQZTJktBz5uRA1fTGxnDmSn6evd4t0',
    appId: '1:697345726797:web:782f5f39808d27cdc2ff04',
    messagingSenderId: '697345726797',
    projectId: 'petasampah-gh2023',
    authDomain: 'petasampah-gh2023.firebaseapp.com',
    storageBucket: 'petasampah-gh2023.appspot.com',
    measurementId: 'G-51T6YXDHD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoflsRIUoQCBfy3P3n9Y0hO6sZG3fqOeo',
    appId: '1:697345726797:android:07ec75f12a7842fbc2ff04',
    messagingSenderId: '697345726797',
    projectId: 'petasampah-gh2023',
    storageBucket: 'petasampah-gh2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtQs-3BmzNIVR5SwZFt0cmOfBMDOR14HY',
    appId: '1:697345726797:ios:3dd550cfa9f9e91dc2ff04',
    messagingSenderId: '697345726797',
    projectId: 'petasampah-gh2023',
    storageBucket: 'petasampah-gh2023.appspot.com',
    iosClientId: '697345726797-mnug29jfoc1rhcmr7r2srpun5ns9v083.apps.googleusercontent.com',
    iosBundleId: 'com.example.petasampah1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtQs-3BmzNIVR5SwZFt0cmOfBMDOR14HY',
    appId: '1:697345726797:ios:3dd550cfa9f9e91dc2ff04',
    messagingSenderId: '697345726797',
    projectId: 'petasampah-gh2023',
    storageBucket: 'petasampah-gh2023.appspot.com',
    iosClientId: '697345726797-mnug29jfoc1rhcmr7r2srpun5ns9v083.apps.googleusercontent.com',
    iosBundleId: 'com.example.petasampah1',
  );
}
